# Generated by Django 2.2.8 on 2020-05-23 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('action_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('adset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_time', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad_Targeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_max', models.IntegerField(default=65)),
                ('age_min', models.IntegerField(default=18)),
                ('genders', models.TextField(blank=True, null=True)),
                ('location_countries', models.TextField(blank=True, null=True)),
                ('location_types', models.TextField(blank=True, null=True)),
                ('publisher_platforms', models.TextField(blank=True, null=True)),
                ('facebook_positions', models.TextField(blank=True, null=True)),
                ('instagram_positions', models.TextField(blank=True, null=True)),
                ('device_platforms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Per_Action_Type',
            fields=[
                ('cost_per_action_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Per_Thruplay',
            fields=[
                ('cost_per_thruplay_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover_Photo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('page_name', models.CharField(default='GEN 42', max_length=30)),
                ('offset_x', models.IntegerField(default=50)),
                ('offset_y', models.IntegerField(default=50)),
                ('source', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insights_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insights_value_id', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('end_time', models.CharField(blank=True, max_length=70, null=True)),
                ('insight_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('insight_name', 'end_time', 'insights_value_id')},
            },
        ),
        migrations.CreateModel(
            name='Post_actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
                ('share', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_tags', models.TextField(blank=True, null=True)),
                ('created_time', models.CharField(max_length=50)),
                ('is_instagram_eligible', models.BooleanField(default=False)),
                ('comments_mirroring_domain', models.CharField(max_length=30)),
                ('shares', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_auth.Post_actions')),
            ],
        ),
        migrations.CreateModel(
            name='Page_Insight',
            fields=[
                ('page_insights_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('values', models.ManyToManyField(to='facebook_auth.Insights_Value')),
            ],
        ),
        migrations.CreateModel(
            name='Outbound_Clicks_Ctr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_clicks_ctr_id', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('outbound_clicks_ctr_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('queryName', models.CharField(blank=True, max_length=50, null=True)),
                ('API', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook_auth.API')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Per_Unique_Outbound_Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unique_outbound_click_id', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('cost_per_unique_outbound_click_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='Cost_Per_Unique_Action_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unique_action_type_id', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('cost_per_unique_action_type_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='Cost_Per_Outbound_Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_outbound_click_id', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('cost_per_outbound_click_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=300)),
                ('objective', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('updated_time', models.CharField(max_length=100)),
                ('stop_time', models.CharField(max_length=100)),
                ('lifetime_budget', models.IntegerField(default=0)),
                ('ads', models.ManyToManyField(related_name='Ad', to='facebook_auth.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Attribution_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_spec_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('window_days', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('attribution_spec_id', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Ad_Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('clicks', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_rate_ranking', models.CharField(blank=True, max_length=100, null=True)),
                ('cpc', models.CharField(blank=True, max_length=100, null=True)),
                ('cpm', models.CharField(blank=True, max_length=100, null=True)),
                ('cpp', models.CharField(blank=True, max_length=100, null=True)),
                ('ctr', models.CharField(blank=True, max_length=100, null=True)),
                ('date_start', models.CharField(blank=True, max_length=100, null=True)),
                ('date_stop', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_rate_ranking', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('impressions', models.CharField(blank=True, max_length=100, null=True)),
                ('reach', models.CharField(blank=True, max_length=100, null=True)),
                ('spend', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_per_action_type', models.ManyToManyField(to='facebook_auth.Cost_Per_Action_Type')),
                ('cost_per_thruplay', models.ManyToManyField(to='facebook_auth.Cost_Per_Thruplay')),
            ],
        ),
        migrations.CreateModel(
            name='Ad_Account_Insight',
            fields=[
                ('clicks', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_start', models.CharField(max_length=50)),
                ('date_stop', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_per_inline_link_click', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_per_inline_post_engagement', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_per_unique_click', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_per_unique_inline_link_click', models.CharField(blank=True, max_length=50, null=True)),
                ('objective', models.CharField(blank=True, max_length=50, null=True)),
                ('actions', models.ManyToManyField(to='facebook_auth.Action')),
                ('cost_per_action_type', models.ManyToManyField(to='facebook_auth.Cost_Per_Action_Type')),
                ('cost_per_outbound_click', models.ManyToManyField(to='facebook_auth.Cost_Per_Outbound_Click')),
                ('cost_per_thruplay', models.ManyToManyField(to='facebook_auth.Cost_Per_Thruplay')),
                ('cost_per_unique_action_type', models.ManyToManyField(to='facebook_auth.Cost_Per_Unique_Action_Type')),
                ('cost_per_unique_outbound_click', models.ManyToManyField(to='facebook_auth.Cost_Per_Unique_Outbound_Click')),
                ('outbound_clicks_ctr', models.ManyToManyField(to='facebook_auth.Outbound_Clicks_Ctr')),
            ],
        ),
        migrations.CreateModel(
            name='Ad_Account',
            fields=[
                ('adaccount_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('account_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_time', models.CharField(blank=True, max_length=30, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_spent', models.CharField(blank=True, max_length=30, null=True)),
                ('balance', models.CharField(blank=True, max_length=30, null=True)),
                ('can_create_brand_lift_study', models.CharField(blank=True, max_length=30, null=True)),
                ('capabilities', models.TextField(blank=True, null=True)),
                ('attribution_spec', models.ManyToManyField(to='facebook_auth.Attribution_Spec')),
                ('campaigns', models.ManyToManyField(related_name='Campaign', to='facebook_auth.Campaign')),
                ('insights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_auth.Ad_Account_Insight')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='insights',
            field=models.ManyToManyField(to='facebook_auth.Ad_Insight'),
        ),
        migrations.AddField(
            model_name='ad',
            name='targeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_auth.Ad_Targeting'),
        ),
        migrations.CreateModel(
            name='Account_Page',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('page_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('access_token', models.TextField(default='EAAt6AfVaOUABAE9aAp2RC33ojOV1Yygn0mFY4qXUL1xgJobZAFgq9O4YCqJQ3tC5Muf7v4eMxuuvv4xP4lJHT0gEyaRuMEwWF8pZAwWBp3dtdVAviTAJVIfQHZA4oyqO6t8k0KFzoDnaGWhGky1g8JiIIK1koYiesyBNzpbfeLp9qQEsHYTTNZAU04acTBECwWAyYtoaxKZBuhk8yUHZAx')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('unseen_message_count', models.IntegerField(blank=True, default=0, null=True)),
                ('unread_message_count', models.IntegerField(blank=True, default=0, null=True)),
                ('unread_notif_count', models.IntegerField(blank=True, default=0, null=True)),
                ('rating_count', models.IntegerField(blank=True, default=0, null=True)),
                ('talking_about_count', models.IntegerField(blank=True, default=0, null=True)),
                ('new_like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('fan_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_owned', models.BooleanField(blank=True, default=False, null=True)),
                ('name_with_location_descriptor', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_eligible', models.BooleanField(blank=True, default=True, null=True)),
                ('overall_star_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('supports_instant_articles', models.BooleanField(blank=True, default=False, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=30, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_auth.Cover_Photo')),
                ('insights', models.ManyToManyField(to='facebook_auth.Page_Insight')),
            ],
        ),
    ]
