# Generated by Django 2.2.8 on 2020-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0003_auto_20200523_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_page',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='name_with_location_descriptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='page_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account',
            name='adaccount_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='account_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='clicks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='cost_per_inline_link_click',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='cost_per_inline_post_engagement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='cost_per_unique_click',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='cost_per_unique_inline_link_click',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='date_start',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='date_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad_account_insight',
            name='objective',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attribution_spec',
            name='attribution_spec_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attribution_spec',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attribution_spec',
            name='window_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cost_per_outbound_click',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_outbound_click',
            name='cost_per_outbound_click_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_outbound_click',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_action_type',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_action_type',
            name='cost_per_unique_action_type_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_action_type',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_outbound_click',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_outbound_click',
            name='cost_per_unique_outbound_click_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cost_per_unique_outbound_click',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cover_photo',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cover_photo',
            name='offset_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cover_photo',
            name='offset_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='insights_value',
            name='insights_value_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='queryName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outbound_clicks_ctr',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outbound_clicks_ctr',
            name='outbound_clicks_ctr_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outbound_clicks_ctr',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page_insight',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page_insight',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page_insight',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.CharField(max_length=100),
        ),
    ]
