# Generated by Django 2.2.8 on 2020-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0004_auto_20200523_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
