# Generated by Django 2.2.8 on 2020-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0005_auto_20200614_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_mirroring_domain',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
