# Generated by Django 2.2.8 on 2020-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0006_auto_20200614_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='actions',
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
