# Generated by Django 2.2.8 on 2020-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0007_auto_20200614_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
