# Generated by Django 2.2.8 on 2020-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0008_auto_20200614_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
