# Generated by Django 2.2.8 on 2020-06-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0012_auto_20200614_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
    ]
