# Generated by Django 2.2.8 on 2020-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0013_remove_post_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
