# Generated by Django 2.2.8 on 2020-06-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0014_post_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
    ]
