# Generated by Django 2.2.8 on 2020-06-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0016_post_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
