# Generated by Django 2.2.8 on 2020-06-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0018_auto_20200615_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_account',
            old_name='last_update_campaigns_insights',
            new_name='last_update_campaigns',
        ),
    ]
