# Generated by Django 2.2.8 on 2020-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0019_auto_20200615_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Campaign',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('niche', models.CharField(blank=True, max_length=100, null=True)),
                ('age_max', models.CharField(blank=True, max_length=30, null=True)),
                ('age_min', models.CharField(blank=True, max_length=30, null=True)),
                ('genders', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.CharField(blank=True, max_length=100, null=True)),
                ('cpc', models.CharField(blank=True, max_length=100, null=True)),
                ('cpm', models.CharField(blank=True, max_length=100, null=True)),
                ('cpp', models.CharField(blank=True, max_length=100, null=True)),
                ('clicks', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('ctr', models.CharField(blank=True, max_length=100, null=True)),
                ('location_types', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('citie', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('device_platforms', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher_platforms', models.CharField(blank=True, max_length=50, null=True)),
                ('positions', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
