# Generated by Django 2.2.8 on 2020-07-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0021_auto_20200708_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience_campaign',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
