# Generated by Django 2.2.8 on 2020-08-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0022_experience_campaign_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
    ]
