# Generated by Django 2.0.7 on 2019-01-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
    ]
