# Generated by Django 2.0.7 on 2019-02-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudoAPI', '0003_auto_20190125_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
