# Generated by Django 2.0.7 on 2019-02-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudoAPI', '0004_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='API',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pseudoAPI.API'),
            preserve_default=False,
        ),
    ]
