# Generated by Django 2.0.7 on 2019-03-03 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudoAPI', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('periodInDays', models.IntegerField(validators=[django.core.validators.MaxValueValidator(91), django.core.validators.MinValueValidator(7)])),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('nextRunDate', models.DateField()),
                ('emailAddress', models.EmailField(max_length=254)),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pseudoAPI.Report')),
            ],
        ),
    ]
